services:

  mgmt:
    build: .
    image: mgmt:latest
    hostname: mgmt
    container_name: mgmt
    environment:
      - container=docker
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/airgap
    stdin_open: true
    ports:
      - 2223:22
    tty: true
    networks:
      local:
        ipv4_address: 10.6.0.11

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1
