services:

  airgap:
    build: .
    image: airgap:0.1
    hostname: airgap
    container_name: airgap
    environment:
      - container=docker
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/airgap
    stdin_open: true
    ports:
      - 2222:22
    tty: true
    networks:
      local:
        ipv4_address: 10.5.0.10

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
