services:

  airgap:
    build: .
    image: airgap-files:latest
    hostname: airgap-files
    container_name: airgap-files
    environment:
      - container=docker
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/airgap
      - .:/host
    stdin_open: true
    ports:
      - 2221:22
    tty: true
    networks:
      local:
        ipv4_address: 10.1.0.10

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1
