services:

  k8snode:
    build: .
    image: k8snode:latest
    hostname: k8snode
    container_name: k8snode
    environment:
      - container=docker
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/airgap
    stdin_open: true
    ports:
      - 2222:22
    tty: true
    networks:
      local:
        ipv4_address: 10.100.0.10

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.1
